repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff check
        entry: pixi run ruff check --fix --show-fixes
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format
        entry: pixi run ruff format
        language: system
        types_or: [python, pyi]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: ["--pattern", "main|^release/.*"]
