version: 2

# Build tools and environment setup
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - git
    - xvfb
    - imagemagick
    - poppler-utils
    - latexmk
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
  # Build commands for HTML and PDF
  commands:
    - curl -fsSL https://pixi.sh/install.sh | bash
    - $HOME/.pixi/bin/pixi install -e docs
    - mkdir -p ~/.casa/data
    - $HOME/.pixi/bin/pixi run -e docs build-docs
    - $HOME/.pixi/bin/pixi run -e docs build-pdf
    - mkdir --parents _readthedocs/html/ _readthedocs/pdf/
    - cp --recursive docs/_build/html/* _readthedocs/html/
    - cp --recursive docs/_build/latex/*.pdf _readthedocs/pdf/
