import logging
import os
import subprocess
import sys

import setuptools
from packaging.version import InvalidVersion, parse
from setuptools import sic
from setuptools.command.build_py import build_py

ENCODING = 'utf-8'


class VersionCommand(setuptools.Command):
    description = 'Generate the version file'
    user_options = [('inplace', 'i', 'Generate the version file in src directory')]
    boolean_options = ['inplace']

    def __init__(self, dist):
        super().__init__(dist)

    def initialize_options(self):
        """Set default values for options."""
        self.inplace = None

    def finalize_options(self):
        # get the path to this file
        dir_path = os.path.dirname(os.path.realpath(__file__))

        if self.inplace:
            self.build_path = dir_path
        else:
            # get the path to the build directory
            build_py_cmd = self.get_finalized_command('build_py')
            self.build_path = os.path.join(dir_path, build_py_cmd.build_lib)

    def run(self):
        version = _get_git_version()
        version_py = os.path.join(self.build_path, 'pipeline', '_version.py')
        self.announce('Creating version file: {}'.format(version_py), level=logging.INFO)
        with open(version_py, 'w', encoding=ENCODING) as f:
            f.write("# File generated by setup.py\n# do not change, do not track in version control\n")
            f.write("version = '{}'\n".format(version))
            f.write('\n')


def _get_git_version() -> str:

    try:
        ver_from_script = subprocess.check_output([sys.executable, 'pipeline/infrastructure/version.py', '--full-string'],
                                                  stderr=subprocess.DEVNULL).decode().strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        # likely the script doesn't exist due to a wrong path or the Git metadata check failed.
        ver_from_script = 'unknown'

    try:
        parse(ver_from_script)
    except InvalidVersion:
        return '0.0.dev0'

    return ver_from_script


class PipelineBuildPyCommand(build_py):
    def run(self):
        build_py.run(self)
        self.run_command('version')


setuptools.setup(
    cmdclass={
        'build_py': PipelineBuildPyCommand,
        'version': VersionCommand,
    },
    # setuptools.sic allows you to bypass the version identifier normalization and
    # preserve the public version label as much as possible, e.g., '1.0.0-dev1' will
    # not get converted to '1.0.0.dev1'.
    # https://github.com/pypa/setuptools/issues/308
    # However, '-' in the local version string,
    # will still be converted to '.', e.g. '1.0.0-dev1+PIPE-1243' will
    # '1.0.0-dev1+PIPE.1243' in the importlib metadata. Therefore we use pipeline/_version.py as
    # the main reference.
    version=sic(_get_git_version())
)
