from __future__ import annotations

import collections.abc
from typing import TYPE_CHECKING

import pipeline.infrastructure.logging as logging
import pipeline.infrastructure.pipelineqa as pqa
import pipeline.infrastructure.utils as utils
import pipeline.qa.scorecalculator as qacalc
import pipeline.h.tasks.exportdata.aqua as aqua
from .flagdeteralmasd import FlagDeterALMASingleDishResults, SerialFlagDeterALMASingleDish, FlagDeterALMASingleDish

if TYPE_CHECKING:
    from pipeline.infrastructure.launcher import Context
    from pipeline.infrastructure.basetask import ResultsList

LOG = logging.get_logger(__name__)


class FlagDeterALMASingleDishQAHandler(pqa.QAPlugin):
    result_cls = FlagDeterALMASingleDishResults
    child_cls = None
    generating_task = SerialFlagDeterALMASingleDish

    def handle(self, context: Context, result: FlagDeterALMASingleDishResults):
        """Generate QA score from result object.

        QA score for pointing outlier is examined.

        Args:
            context: Pipeline context object.
            result: Result object generated by hsd_flagdata task.
        """
        vis = result.inputs['vis']
        pointing = result.inputs['pointing']
        ms = context.observing_run.get_ms(vis)

        score = qacalc.score_pointing_outlier(
            ms,
            pointing,
            result.pointing_outlier_stats
        )
        result.qa.pool.extend(score)


class FlagDeterALMASingleDishListQAHandler(pqa.QAPlugin):
    result_cls = collections.abc.Iterable
    child_cls = FlagDeterALMASingleDishResults
    generating_task = FlagDeterALMASingleDish

    def handle(self, context: Context, result: ResultsList):
        """Attach QA scores to ResultsList object.

        Collate QA scores from child results and attach
        them to ResultsList object.

        Args:
            context: Pipeline context object.
            result: ResultsList object generated by hsd_flagdata task.
        """
        # collate the QAScores from each child result, pulling them into our
        # own QAscore list
        collated = utils.flatten([r.qa.pool for r in result])
        result.qa.pool.extend(collated)


aqua_exporter = aqua.xml_generator_for_metric('NumberOfPointingOutliers', '{:d}')
aqua.register_aqua_metric(aqua_exporter)
