"""QA score module for applycal task."""
from __future__ import annotations

import collections.abc
from typing import TYPE_CHECKING

import pipeline.infrastructure.logging as logging
import pipeline.infrastructure.pipelineqa as pqa
import pipeline.infrastructure.utils as utils
import pipeline.h.tasks.exportdata.aqua as aqua
import pipeline.qa.scorecalculator as qacalc
from .applycal import SDApplycalResults, SerialSDApplycal, SDApplycal

if TYPE_CHECKING:
    from pipeline.infrastructure.basetask import ResultsList
    from pipeline.infrastructure.launcher import Context

LOG = logging.get_logger(__name__)


class SDApplycalQAHandler(pqa.QAPlugin):
    result_cls = SDApplycalResults
    child_cls = None
    generating_task = SerialSDApplycal

    def handle(self, context: Context, result: SDApplycalResults):
        """Register QA scores generated by analyse method of SerialSDApplycal task.

        Args:
            context: Pipeline context object.
            result: Result object generated by hsd_applycal task.
        """
        result.qa.pool.extend(result.xy_deviation_score)
        scores = []
        scores = qacalc.score_amp_vs_time_plots(context, result)
        result.qa.pool.extend(scores)


class SDApplycalListQAHandler(pqa.QAPlugin):
    result_cls = collections.abc.Iterable
    child_cls = SDApplycalResults
    generating_task = SDApplycal

    def handle(self, context: Context, result: ResultsList):
        """Attach QA scores to ResultsList object.

        Collate QA scores from child results and attach
        them to ResultsList object.

        Args:
            context: Pipeline context object.
            result: ResultsList object generated by hsd_flagdata task.
        """
        # collate the QAScores from each child result, pulling them into our
        # own QAscore list
        collated = utils.flatten([r.qa.pool for r in result])
        result.qa.pool.extend(collated)


aqua_exporter_ampvstime = aqua.xml_generator_for_metric('AmpVsTimePlotQuality', '{:0.3f}')
aqua_exporter_xxyydev = aqua.xml_generator_for_metric('XX-YY.deviation', '{:d}')
aqua.register_aqua_metric(aqua_exporter_ampvstime)
aqua.register_aqua_metric(aqua_exporter_xxyydev)
