#!/usr/bin/env python
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
#
#

import os
import sys
import textwrap
from datetime import datetime, timezone

pipeline_src = os.getenv('pipeline_src')
if pipeline_src is not None:
    # Use the env variable "pipeline_src" to look for Pipeline if it's specified.
    sys.path.insert(0, os.path.abspath(pipeline_src))
else:
    # Use the ancestry path if "pipeline_src" is not set.
    sys.path.insert(0, os.path.abspath('../../'))

# Make local extensions importable.
sys.path.insert(0, os.path.abspath('_extension'))

try:
    import pipeline
    from pipeline.h.tasks import ImportData
    from pipeline.infrastructure.api import Inputs, Results, Task
    from pipeline.infrastructure.renderer.regression import get_all_subclasses

    taskclasses_str = [ret0.__module__ + '.' + ret0.__name__ for ret0 in get_all_subclasses(Task)]
    inputsclasses_str = [ret0.__module__ + '.' + ret0.__name__ for ret0 in get_all_subclasses(Inputs)]
    resultsclasses_str = [ret0.__module__ + '.' + ret0.__name__ for ret0 in get_all_subclasses(Results)]
    importdataclasses_str = [ret0.__module__ + '.' + ret0.__name__ for ret0 in get_all_subclasses(ImportData)]

    # create custom directives to create inheritance diagrams for all Task/Inputs Classes
    #   https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#substitution-definitions
    #   https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_prolog

    rst_epilog = r"""
        .. |taskclasses_diagram| inheritance-diagram:: {}
            :parts: -1
        .. |inputsclasses_diagram| inheritance-diagram:: {}
            :parts: -1
        .. |resultsclasses_diagram| inheritance-diagram:: {}
            :parts: -1
        .. |importdataclasses_diagram| inheritance-diagram:: {}
            :parts: -1
        """.format(
        ' '.join(taskclasses_str),
        ' '.join(inputsclasses_str),
        ' '.join(resultsclasses_str),
        ' '.join(importdataclasses_str),
    )
    rst_epilog = textwrap.dedent(rst_epilog)

except ImportError as error:
    print("Can't import Pipeline, but we will continue to build the docs.")
    print(error.__class__.__name__ + ': ' + error.message)
    pass


def setup(app):
    # Raise docutils substitution line-length limit (default 10 000) so that
    # the Task inheritance diagram substitution (~14 500 chars) is not dropped.
    app.connect('builder-inited',
                lambda app: app.env.settings.update({'line_length_limit': 20_000}))


# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    # --------
    # https://docs.readthedocs.io/en/stable/guides/jupyter.html#using-notebooks-in-other-formats
    # option 1 # better integration with intersphinx
    'myst_nb',  # Handles both notebooks and plain markdown files
    # option 2 # https://github.com/executablebooks/MyST-NB/issues/421
    # 'myst_parser',  # Not needed with myst_nb
    # 'nbsphinx',
    # ---------
    'sphinx.ext.autodoc',
    # 'autoapi.extension',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.autosummary',
    'sphinx.ext.todo',
    'sphinx_markdown_tables',
    'sphinx.ext.coverage',
    'sphinx.ext.imgconverter',
    'sphinxcontrib.mermaid',
    'sphinx.ext.mathjax',
    'sphinx.ext.napoleon',
    'sphinx.ext.githubpages',
    # 'sphinx.ext.intersphinx',
    'sphinx.ext.inheritance_diagram',
    'sphinx_automodapi.automodapi',
    'sphinx_automodapi.smart_resolver',
    'sphinxcontrib.bibtex',
    'sphinx_astrorefs',
    'sphinx.ext.graphviz',
    'sphinx.ext.viewcode',
    'sphinx_copybutton',
    'IPython.sphinxext.ipython_console_highlighting',
    'IPython.sphinxext.ipython_directive',
    'cli_function_stubs',
    'parameter_linking',
]

add_module_names = False
autosectionlabel_prefix_document = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# PIPE-2854: diable smartquotes
smartquotes = False

# The suffix(es) of source filenames.
# MyST parser handles both .rst and .md files automatically when enabled
# (myst_nb and myst_parser both register .md suffix)
# source_suffix = {
#    '.rst': 'restructuredtext',
#    '.md': 'markdown',
# }

# for nbsphinx/notebook-markdown: handle markdown using jupytext
# nbsphinx_custom_formats = {
#     ".md": ["jupytext.reads", {"fmt": "mystnb"}],
# }

# for myst-nb/notebook-markdown: handle markdown using jupytext
# nb_custom_formats = {
#     ".md": ["jupytext.reads", {"fmt": "mystnb"}],
# }

# The master toctree document.
master_doc = 'index'

# https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-release
release = build_version = pipeline.environment.pipeline_revision  # used on the PDF cover
version = build_version.split('+')[0]

# remove -detached suffix as readthedocs always uses git checkout --force to create a
# detached state
build_version_short = build_version.removesuffix('-detached')

# General information about the project.
project = f'Pipeline ({version})'
html_title = f'Pipeline ({version})'
author = 'Pipeline Dev. Team'
copyright = f'2020–{datetime.now(timezone.utc).year}, {author}, build: {build_version_short}'

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
# version = pipeline.__version__
# The full version, including alpha/beta/rc tags.
# release = pipeline.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', '**.ipynb_checkpoints', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'  # 'sphinx', 'github-dark', ' default'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# sphinx-copybutton
copybutton_prompt_text = r'>>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: '
copybutton_prompt_is_regexp = True
copybutton_remove_prompts = True
copybutton_copy_empty_lines = False
copybutton_only_copy_prompt_lines = True

# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'furo'

# Theme options for furo; empty dict means all defaults (including default fonts).
html_theme_options = {
    'footer_icons': [],
}
# html_logo = "_static/favicon.ico"
html_favicon = '_static/favicon-16x16.png'
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will override the builtin "default.css".
html_static_path = ['_static']
html_css_files = ['custom_theme.css']
html_js_files = ['furo_layout.js']

# -- Options for Mermaid output ---------------------------------------

mermaid_d3_zoom = True
myst_fence_as_directive = ['mermaid']

# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'pipeline_doc'

html_baseurl = ''

# -- Options for LaTeX output ------------------------------------------

latex_elements = {
    'papersize': 'letterpaper',  # or 'a4parper'
    'pointsize': '10pt',
    # Preamble for custom packages and settings
    # Sphinx will use this string when it loads the geometry package and we avoid it in preamble.
    'geometry': r'\usepackage[top=1.0in, bottom=1.0in, left=0.5in, right=0.5in]{geometry}',
    'preamble': r"""
  \usepackage{hyperref}
  % \usepackage{extsizes} % required to use font sizes other than 10, 11, or 12pt
  \usepackage{longtable}
  \setcounter{tocdepth}{1}
  \protected\def\sphinxcode#1{\textcolor{red}{\texttt{#1}}}
  \makeatletter
  \renewcommand{\sphinxtableofcontents}{%
    \pagenumbering{roman}%
    \begingroup
      \parskip \z@skip
      \sphinxtableofcontentshook
      \tableofcontents
    \endgroup
    % before resetting page counter, let's do the right thing.
    \if@openright\cleardoublepage\else\clearpage\fi
    \pagenumbering{arabic}% 
    \makeatother
    }
""",
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
    # remove blank pages (between the title page and the TOC, etc.)
    #
    'classoptions': ',openany,oneside',
    'babel': '\\usepackage[english]{babel}',
}

# If false, no module index is generated.
latex_use_modindex = False

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto, manual, or own class]).
latex_documents = [('latex', 'taskdocs.tex', 'Pipeline Tasks Reference Manual', 'pipeline team', 'manual')]


# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, 'pipeline', 'Pipeline Documentation', [author], 1)]


# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'pipeline', 'Pipeline @ NRAO Documentation', author, 'pipeline', 'placeholder', 'Miscellaneous')
]

# -- Sidebars

# furo provides its own sidebar; custom per-page sidebars are not supported
html_sidebars = {}

# -- napoleon

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = False
napoleon_attr_annotations = True


verbatimwrapslines = False
html_show_sourcelink = True
autosummary_generate = True
autosummary_generate_overwrite = False  # only write stubs that don't exist yet; speeds up incremental builds

# https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#confval-autosummary_ignore_module_all
# Avoid documenting re-imported names (typing.Any, datatype.DataType, domain.MeasurementSet, ...) as
# attributes of every module that does `from ... import X`. Without this, each `from typing import Any`
# registers `pipeline.<pkg>.Any` as a documented attribute, producing dozens of ambiguous cross-reference
# targets and a huge slow-down of the `writing output...` phase. Re-exports listed in a module's __all__
# are still emitted because `autosummary_ignore_module_all = False`.
autosummary_imported_members = False
autosummary_ignore_module_all = False  # respect `__all__` in autosummary to get clean output

# Suppress duplicate-target warnings from the python domain. The pipeline package legitimately re-exports
# many classes (Context, MeasurementSet, SpectralWindow, Field, Source, Antenna, DataType, ...) at both
# the package and submodule level. Sphinx still resolves these refs (smart_resolver picks one), but
# rendering the multi-KB warning text once per occurrence dominated wall time during `writing output...`.
suppress_warnings = ['ref.python']

autodoc_mock_imports = [
    "casaconfig",
    "casaplotms",
    "casashell",
    "casatasks",
    "casatools",
]
# autodoc_default_options = ['members']

# Move type hints from signature to parameter descriptions for cleaner display
autodoc_typehints = 'description'  # 'signature' or 'none'

autodoc_default_options = {
    # other options
    'show-inheritance': True
}

# sphinx-automodapi: https://sphinx-automodapi.readthedocs.io
numpydoc_show_class_members = False
automodapi_toctreedirnm = '_automodapi'
automodsumm_included_members = ['__init__']
automodsumm_inherited_members = False

# -- intersphinx

# intersphinx_mapping = {
#     'python': ('https://docs.python.org/3',(None, 'python-inv.txt')),
#     'astropy': ('http://docs.astropy.org/en/latest/', None),
#     'pyerfa': ('https://pyerfa.readthedocs.io/en/stable/', None),
#     'pytest': ('https://pytest.readthedocs.io/en/stable/', None),
#     'ipython': ('https://ipython.readthedocs.io/en/stable/', None),
#     'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
#     'sphinx_automodapi': ('https://sphinx-automodapi.readthedocs.io/en/stable/', None),
#     'packagetemplate': ('http://docs.astropy.org/projects/package-template/en/latest/', None),
#     'h5py': ('http://docs.h5py.org/en/stable/', None),
#     "sphinx": ("https://www.sphinx-doc.org/en/master/", None),
# }
# intersphinx_disabled_reftypes = ["*"]

# sphinxcontrib.bibtex/sphinx-astrorefs
bibtex_bibfiles = ['references/pipeline-resolved.bib']
bibtex_encoding = 'utf-8'
astrorefs_resolve_aas_macros = True
astrorefs_resolve_aas_macros_infile = 'references/pipeline.bib'
astrorefs_resolve_aas_macros_outfile = 'references/pipeline-resolved.bib'

# autoapi

autoapi_dirs = ['../../pipeline']

# inheritance_graph_attrs = dict(rankdir="TB", size='""')

inheritance_graph_attrs = {'rankdir': 'LR', 'size': '"25.0, 50.0"', 'bgcolor': 'whitesmoke'}

inheritance_node_attrs = {
    'shape': 'box',
    'fontsize': 12,
    'height': 0.25,
    'fontname': '"Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans"',
    'style': '"setlinewidth(0.5),filled"',
    'fillcolor': 'white',
}

inheritance__edge_attrs = {'arrowsize': 0.5, 'style': '"setlinewidth(0.5)"'}


# nbsphinx
html_sourcelink_suffix = ''
nbsphinx_allow_errors = True
nbsphinx_execute = 'never'
nbsphinx_codecell_lexer = 'python3'
# nbsphinx_input_prompt='[%s]: '
# nbsphinx_output_prompt='[%s]: '

nbsphinx_epilog = """
----

Generated by nbsphinx_ from a Jupyter_ notebook.

.. _nbsphinx: https://nbsphinx.readthedocs.io/
.. _Jupyter: https://jupyter.org/
"""


nbsphinx_prolog = r"""

{% set docname = env.doc2path(env.docname, base=None)|string %}

.. only:: html

    Generated by nbsphinx_ from a Jupyter_ `{{ docname }}`_

        .. _nbsphinx: https://nbsphinx.readthedocs.io/
        .. _Jupyter: https://jupyter.org/
        .. _{{ docname }}: https://github.com/r-xue/pipeline/blob/gh-pages/html/{{ docname }}
    

.. raw:: latex

    \nbsphinxstartnotebook{The following section was created from
    \texttt{\strut{}{{ docname }}}:}
----
"""


# myst-parser

myst_enable_extensions = [
    'amsmath',
    'attrs_inline',
    'colon_fence',
    'deflist',
    'dollarmath',
    'fieldlist',
    'html_admonition',
    'html_image',
    'linkify',
    'replacements',
    'smartquotes',
    'strikethrough',
    'substitution',
    'tasklist',
]
myst_linkify_fuzzy_links = False


# myst-NB

nb_execution_mode = 'off'
